### ISSUE TITLE
check

### ISSUE THREAD

**Issue by Hser2bio** [liamprodev/NFT-chakra-truffle#1]

**Comment by liamprodev** [comment]
Don't disturb my working..

**Comment by georgeportillo** [comment]
then don't fuck with my company

@Hser2bio do you know this person?

**Comment by Hser2bio** [comment]
Hi @georgeportillo 

When i wrote this commit was because i suppose that he is The same person than this user, who is a Scammer too: https://github.com/liamprodev

sorry if he fucked you! shit scammers
